// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:40f2c64b-0f4b-42ab-8e1b-a4ad6d47e677",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_YEARfZuYd",
    "aws_user_pools_web_client_id": "10d7jgngp2d3bjoh3jvjia0cn1"
};


export default awsmobile;
